spring:
  application:
    name: cloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/mscourserelm     
          
server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://cursoms-eureka-user:ecok-usr-eeuramssur@${EUREKA_SERVER}:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: '*' 
        
logging:
  file:
    name: ./logs/log-file.log             
                  
#sudo docker run --name cursokeycloak -p 8081:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:18.0.0 start-dev